# Generated by Django 2.2.1 on 2019-05-20 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190520_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='category',
            new_name='article_category',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='series',
            new_name='article_series',
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 17, 25, 29, 553877), verbose_name='date published'),
        ),
    ]
