# Generated by Django 2.2.1 on 2019-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190520_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='series',
            new_name='article_series',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='article_slug',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='article_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='category',
            new_name='article_category',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='article_series',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
