# Generated by Django 2.2.1 on 2019-05-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190520_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_slug',
            new_name='article_directory',
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='category_slug',
            new_name='category_directory',
        ),
    ]
