# Generated by Django 2.2.1 on 2019-06-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_article_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_series',
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.ArticleCategory', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='ArticleSeries',
        ),
    ]
